/**
 * @fileoverview reCAPTCHA verification service for Google reCAPTCHA v2 and v3.
 * Provides backend verification of reCAPTCHA tokens generated by the frontend.
 *
 * @module recaptcha
 */

import express, { Router, Request, Response } from "express";
const appRecaptcha = Router();
import dotenv from "dotenv";
import path from "path";
import axios from "axios";
// Use URLSearchParams for URL encoding
import { URLSearchParams } from "url";

dotenv.config({ path: path.resolve(__dirname, "../.env") });

appRecaptcha.use(express.json());

/**
 * Verifies a reCAPTCHA token with Google's API.
 *
 * @route POST /api/recaptcha/verify-captcha
 * @param {Request} req - Express request object
 * @param {string} req.body.token - reCAPTCHA token from frontend
 * @param {string} [req.body.version="v3"] - reCAPTCHA version ("v2" or "v3")
 * @param {Response} res - Express response object
 *
 * @returns {Promise<void>} JSON response with verification result
 *
 * @example
 * // Request body:
 * {
 *   "token": "03AGdBq24PBCd...",
 *   "version": "v3"
 * }
 *
 * // Success response (v3):
 * {
 *   "verified": true,
 *   "score": 0.9
 * }
 *
 * // Success response (v2):
 * {
 *   "verified": true
 * }
 *
 * // Failure response:
 * {
 *   "verified": false,
 *   "message": "Verification failed",
 *   "errorCodes": ["invalid-input-response"]
 * }
 *
 * @description
 * **v3 Verification**:
 * - Requires score >= 0.5 to pass
 * - Returns score in response
 *
 * **v2 Verification**:
 * - Binary pass/fail (checkbox validation)
 * - No score returned
 *
 * Uses environment variables:
 * - `GOOGLE_RECAPTCHA_V3_SECRET` for v3
 * - `GOOGLE_RECAPTCHA_V2_SECRET` for v2
 */
appRecaptcha.post("/verify-captcha", async (req: Request, res: Response) => {
  const token = req.body.token;
  const version = req.body.version || "v3";
  const secret = version === "v3" ? process.env.GOOGLE_RECAPTCHA_V3_SECRET : process.env.GOOGLE_RECAPTCHA_V2_SECRET;
  if (!secret) {
    return res.status(500).send({ verified: false, message: "Server configuration error" });
  }
  const googleVerifyUrl = `https://www.google.com/recaptcha/api/siteverify`;

  // Prepare the data to be sent in the request body
  const params = new URLSearchParams();
  params.append("secret", secret);
  params.append("response", token);

  try {
    // Make the POST request with URL-encoded form data
    const response = await axios.post(googleVerifyUrl, params.toString(), {
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
    });

    const { success, score } = response.data;
    if (version === "v3" && success && score >= 0.5) {
      res.send({ verified: true, score });
    } else if (version === "v2" && success) {
      res.send({ verified: true });
    } else {
      res.send({
        verified: false,
        message: "Verification failed",
        errorCodes: response.data["error-codes"],
      });
    }
  } catch (error) {
    console.error("Error during reCAPTCHA verification:", error);
    res.status(500).send({ verified: false, message: "Server error" });
  }
});

export default appRecaptcha;
